
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sagor
 */
public class project extends javax.swing.JFrame {

    /**
     * Creates new form project
     */
    String [] s ={"Anger rape" ,"Power assertive rapist",
"Neuropsychological Processes","Deviant Sexual Preferences" ,
"Personality Disorders and Traits","Cognitive and Attitudinal Biases","Insecure Attachment Lens",
"Known victim",
"Drug facilitated sexual assault","Sexual gratification",
"Psychological factors" ,
"Research on convicted rapists",
"Social factors"}; 
    public project() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 50));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(180, 40, 320, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Search");
        jButton2.setAutoscrolls(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(530, 40, 80, 30);

        jList2.setBackground(new java.awt.Color(0, 51, 51));
        jList2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jList2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jList2.setForeground(new java.awt.Color(255, 255, 255));
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Anger rape", "Power assertive rapist", "Sadistic rape", "Cognitive and Attitudinal Biases", "Neuropsychological Processes", "Deviant Sexual Preferences", "Insecure Attachment Lens", "Known victim", "Drug facilitated sexual assault", "Sexual gratification", "Psychological factors", "Research on convicted rapists", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 70, 180, 470);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contents");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 40, 110, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(190, 80, 490, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        String a =jTextField1.getText().toString();
        for(int i=0;i<a.length();i++)
        {
            if(a.equals(s[0])){
               jTextArea1.setText("The goal of this rapist is to humiliate, debase and hurt their victim; they express their contempt for their victim through physical violence and profane language. For these rapists, sex is a weapon to defile and degrade the victim, rape constitutes the ultimate expression of their anger. This rapist considers rape the ultimate offense they can commit against the victim.\n" +
"\n" +
"Anger rape is characterized by physical brutality, much more physical force is used during the assault than would be necessary if the intent were simply to overpower the victim and achieve penetration. This type of offender attacks their victim by grabbing, striking and knocking the victim to the ground, beating them, tearing their clothes, and raping them.\n" +
"\n" +
"The experience for the offender is one that is of conscious anger and rage.");
            }
            if(a.equals(s[1])){
                jTextArea1.setText("For these rapists, rape becomes a way to compensate for their underlying feelings of inadequacy and feeds their issues of mastery, control, dominance, strength, intimidation, authority and capability. The intent of the power rapist is to assert their competency. The power rapist relies upon verbal threats, intimidation with a weapon, and only uses the amount of force necessary to subdue the victim.\n" +
"\n" +
"The power rapist tends to have fantasies about sexual conquests and rape. They may believe that even though the victim initially resists them, that once they overpower their victim, the victim will eventually enjoy the rape. The rapist believes that the victim enjoyed what was done to them, and they may even ask the victim to meet them for a date later. (Citation needed)\n" +
"\n" +
"Because this is only a fantasy, the rapist does not feel reassured for long by either their own performance or the victim's response. The rapist feels that they must find another victim, convinced that this victim will be \"the right one\".\n" +
"\n" +
"Hence, their offenses may become repetitive and compulsive. They may commit a series of rapes over a short period of time.");
            }
            
            if(a.equals(s[2])){
                jTextArea1.setText("The neuropsychological deficits that may contribute to a propensity for sexual assault include difficulties in self-regulation, executive functioning problems, perception/memory system problems, arousal/motivation system deficits, and problems in the action selection system[12]. The difficulties arise when sexual aggressors aren’t able to understand their emotional states and when confronted with a situation that trigger their arousal/motivation systems, they become confused and may have issues controlling their behavior[13]. An inability to adapt plans to deal with unforeseen situations or having limited problem-solving skills (the action selection system) and maintaining maladaptive beliefs categorized by erroneous interpretations of social encounters (perception/memory systems) can also contribute to a greater susceptibility to commit acts of sexual violence[14].");
            }
            
            if(a.equals(s[3])){
                jTextArea1.setText("Research focusing on the deviant sexual preferences propensity model suggests that people who perpetrate acts of sexual violence are sexually aroused by non-consensual sexual interactions more than consensual sexual interactions. The research that seeks to support this model (penile plethysmography) has not been able to reliably find differences in the two different groups of males (those who have committed acts of sexual aggression and those who have not)[15]. Instead, the studies are providing more evidence for the cognitive, attitudinal, neuropsychological, and lifestyle differences that impact sexual arousal in certain situations, rather than a deviant sexual preference leading to a higher propensity for sexual violence.");
            }
            
            if(a.equals(s[4])){
                jTextArea1.setText("The last propensity model of sexual violence views the perpetrators of sexual violence through 3 lenses of different personality traits, with interpersonal functioning being the most important factor in whether a person will have a higher propensity for sexual violence. This model is based on the idea that sexual aggression is indicative of problems starting and managing enjoyable intimate relationships");
            }
            
            if(a.equals(s[5])){
                jTextArea1.setText("The cognitive traits and attitudinal biases associated with a propensity to commit acts of sexual aggression come from socio-cultural research and says that forms of sexual aggression come from false beliefs of gender relations, misdirected objectives (i.e. only dating to have sex), and erroneous impressions of social interactions (linked to gender relations)[9]. Research focusing specifically on gender relations within the context of sexual assault have found that conformance to notions of male entitlement, suspicion of the opposite sex, perceiving violence as a reasonable method for solving problems, and holding the traditional patriarchal attitudes that specific societal roles belong to specific genders are found to adhere to the concept of male entitlement/superiority (in the context of gender relations)[10]. The cognitive biases that add to one's propensity to commit acts of sexual violence include the belief that women are sex objects; men’s sexual drive is uncontrollable; a feeling of entitlement (entitlement to sex); society is dangerous; and that women are unpredictable and dangerous[11] .");
            }
            
            if(a.equals(s[6])){
                jTextArea1.setText("The insecure attachment style lens stems from research done on sexual aggressors that characterized them as people who had insecure attachment styles (as a result of child abuse, parental divorce, etc.) manifested as low self-esteem, an inability to develop relationships with others, and significant emotional loneliness[19]. Through the lens of this model, sexual aggression is used as a faulty means of fulfilling intimacy needs.");
            }
            
            if(a.equals(s[7])){
                jTextArea1.setText("Data on sexually violent individuals show that most direct their acts at individuals whom they already know.[");
            }
            
            if(a.equals(s[8])){
                jTextArea1.setText("Drug-facilitated sexual assault (DFSA), also known as predator rape, is a sexual assault carried out after the victim has become incapacitated due to having consumed alcoholic beverages or other drugs. Alcohol has been shown to play a disinhibiting role in certain types of sexual assault,[26] as have some other drugs, notably cocaine.[27] Alcohol has a psychopharmacological effect of reducing inhibitions, clouding judgements and impairing the ability to interpret cues.[28] The biological links between alcohol and violence are, however, complex.[26] Research on the social anthropology of alcohol consumption suggests that connections between violence, drinking and drunkenness are socially learned rather than universal.[29] Some researchers have noted[citation needed] that alcohol may act as a cultural break time, providing the opportunity for antisocial behavior. Thus people are more likely to act violently when drunk because they do not consider that they will be held accountable for their behavior. Some forms of group sexual violence are also associated with drinking. In these settings, consuming alcohol is an act of group bonding, where inhibitions are collectively reduced and individual judgment ceded in favor of the group.");
            }
            
            if(a.equals(s[9])){
                jTextArea1.setText("In 1994, Richard Felson coauthored the controversial book \"Aggression and Coercive Actions: A Social-Interactionist Perspective\" with James Tedeschi, a book which argues that sexual entitlement is the motive of rapists, rather than the aggressive desire to dominate the victim.[30] Felson believes that rape is an aggressive form of sexual coercion and the goal of rape is sexual entitlement and to gain a sense of power. Meta-analyses indicate that convicted rapists demonstrate greater sexual arousal to scenes of sexual coercion involving force than do non-rapists.[31] In one study, male rapists evaluated with penile plethysmography demonstrated more arousal to forced sex and less discrimination between forced and consensual sex than non-rapist control subjects, though both groups responded more strongly to consensual sex scenarios.");
            }
            
            if(a.equals(s[10])){
                jTextArea1.setText("There has been considerable research in recent times on the role of cognitive variables among the set of factors that can lead to rape. A detailed conceptual analysis shows that objectification might underlie denial of agency and personhood that leads to rape.[5] Sexually violent men have been shown to be more likely to consider victims responsible for the rape and are less knowledgeable about the impact of rape on victims.[33] Such men may misread cues given out by women in social situations and may lack the inhibitions that act to suppress associations between sex and aggression.[33] They may have coercive sexual fantasies,[34] and overall are more hostile towards women than are men who are not sexually violent.[35][36][37] In addition to these factors, sexually violent men are believed to differ from other men in terms of impulsivity and antisocial tendencies.[38] They also tend to have an exaggerated sense of masculinity. Sexual violence is also associated with a preference for impersonal sexual relationships as opposed to emotional bonding[dubious – discuss], with having many sexual partners and with the inclination to assert personal interests at the expense of others.[37][39] A further association is with adversarial attitudes on gender, that hold that women are opponents to be challenged and conquered.");
            }
            
            if(a.equals(s[11])){
                jTextArea1.setText("The research on convicted rapists has found several important motivational factors in the sexual aggression of males. Those motivational factors repeatedly implicated are having anger at women and having the need to control or dominate them. Additionally, as reported by several rapists they are finely attracted by the wearings of women.[41]\n" +
"\n" +
"A study by Marshall et al. (2001) found that male rapists had less empathy toward women who had been sexually assaulted by an unknown assailant and more hostility toward women than non-sex-offenders and nonoffender males/females.[42]\n" +
"\n" +
"Meta-analyses indicate that convicted rapists demonstrate greater sexual arousal to scenes of sexual coercion involving force than do non-rapists");
            }
            
            if(a.equals(s[12])){
                jTextArea1.setText("Factors operating at a societal level that influence sexual violence include laws and national policies relating to gender equality in general and to sexual violence more specifically, as well as norms relating to the use of violence. While the various factors operate largely at local level, within families, schools, workplaces and communities, there are also influences from the laws and norms working at national and even international level.");
            }
            
            /*  if(a.equals(s[13])){
                jTextArea1.setText("");
            }
            
            if(a.equals(s[1])){
                jTextArea1.setText("");
            }
            
            if(a.equals(s[1])){
                jTextArea1.setText("");
            }
            
            if(a.equals(s[1])){
                jTextArea1.setText("");
            }*/
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid search");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
